- defaults:
    link:
        create: true
        relink: true
        force: true

- clean: ['~', '~/.config', '~/.virtualenvs']

- link:
    ~/.antigen.zsh: .antigen.zsh
    ~/.zshrc: zshrc
    ~/.zsh_packages: zsh_packages
    ~/.config/fish: fish
    ~/.tmux.conf: tmuxrc
    ~/.vimrc: vimrc
    ~/.yabairc: yabairc
    ~/.skhdrc: skhdrc
    ~/.config/nvim/init.vim: nvim/init.vim
    ~/.config/nvim/lua/cfg/treesitter.lua: nvim/lua/cfg/treesitter.lua
    ~/.gnupg/gpg.conf: gpg.conf
    ~/.gnupg/gpg-agent.conf: gpg-agent.conf
    ~/.virtualenvs/postactivate: virtualenvs/postactivate
    ~/.atom/config.cson: atom/config.cson
    ~/.atom/init.coffee: atom/init.coffee
    ~/.atom/keymap.cson: atom/keymap.cson
    ~/.atom/pkgs: atom/pkgs
    ~/.atom/snippets.cson: atom/snippets.cson
    ~/.atom/styles.less: atom/styles.less

- shell:
    - [bash .scripts/atom_pkgs.sh, updating Atom packages (if possible)]
    - [bash .scripts/nvim_dein.sh, installing dein for nvim]
